# Hypothesis Testing

## 1. Z Test

### Example 1:
A teacher claims that the mean score of students in his class is greater than 82 
with a standard deviation of 20. If a sample of 81 students was selected with a 
mean score of 90.

In [1]:
import scipy.stats as st # Library with constants in which stats has statistical analysis
import numpy as np

In [2]:
sample_mean = 90
population_mean = 82
population_std = 20
n = 81
alpha = 0.05 # Assume

In [3]:
z_calc = (sample_mean - population_mean) / (population_std / np.sqrt(n))
z_calc

np.float64(3.5999999999999996)

In [4]:
z_table = st.norm.ppf(1-alpha) # norm contains functions related to normal distribution
z_table

np.float64(1.6448536269514722)

In [5]:
if z_table < z_calc:
    print("Teacher is right")
else:
    printf("Teacher is wrong")

Teacher is right


### Example 2:
##### Scenario:
Imagine you work for an e-commerce company, and your team is responsible for 
analyzing customer purchase data. You want to determine whether a new website 
design has lead to a significant increase in the average purchase amount 
compared to the old design.
##### Data:
You have collected data from a random sample of 30 customers who made purchase on the 
old website design and 30 customers who made purchase on the new website design. 
You have the sample means, sample standard deviations, and sample sizes for both groups.
- Old design data = [45.2, 42.8, 38.9, 43.5, 41.0, 44.6, 40.5, 42.7, 39.8, 41.4, 44.3, 
                          39.7, 42.1, 40.6, 43.0, 42.2, 41.5, 39.6, 44.0, 43.1, 38.7, 43.9, 
                          42.0, 41.9, 42.8, 43.7, 41.3, 40.9, 42.5, 41.6]
- New design data = [48.5, 49.1, 50.2, 47.8, 48.7, 49.9, 48.0, 50.5, 49.8, 49.6, 48.2, 48.9, 
                         49.7, 50.3, 49.4, 50.1, 48.6, 48.3, 49.0, 50.0, 48.4, 49.3, 49.5, 48.8, 
                         50.6, 50.4, 48.1, 49.2, 50.7, 50.8]
- Population standard deviation = 2.5



In [6]:
import scipy.stats as st
import numpy as np

In [7]:
# Convert the given list to np.array for fast calculation
Old_design_data = np.array([45.2, 42.8, 38.9, 43.5, 41.0, 44.6, 40.5, 42.7, 39.8, 41.4, 44.3, 
                          39.7, 42.1, 40.6, 43.0, 42.2, 41.5, 39.6, 44.0, 43.1, 38.7, 43.9, 
                          42.0, 41.9, 42.8, 43.7, 41.3, 40.9, 42.5, 41.6])
New_design_data = np.array([48.5, 49.1, 50.2, 47.8, 48.7, 49.9, 48.0, 50.5, 49.8, 49.6, 48.2, 48.9, 
                         49.7, 50.3, 49.4, 50.1, 48.6, 48.3, 49.0, 50.0, 48.4, 49.3, 49.5, 48.8, 
                         50.6, 50.4, 48.1, 49.2, 50.7, 50.8])


In [8]:
pop_std = 2.5
n_sp = len(New_design_data) # 30
alpha = 0.05 # Assume

In [9]:
mean_new = np.mean(New_design_data)
mean_old = np.mean(Old_design_data)

In [10]:
z_calc = (mean_new - mean_old) / (pop_std / np.sqrt(n_sp))
z_calc

np.float64(16.11034615808528)

In [11]:
z_table = st.norm.ppf(1-alpha)
z_table

np.float64(1.6448536269514722)

In [12]:
if z_calc > z_table:
    print("New website is better than old")
else:
    print("New website is same as old")

New website is better than old


## 2. T Test

### Example 1:
A manufracturer claims that the average weight of a bag of potato chips is 150 grams. 
A sample of 25 bags is taken and the average weight is found to be 148 grams, with 
a standard deviation of 5 grams. Test the manufacturer's claim using a one-tailed t-test 
with a significance level of 0.05

In [13]:
import scipy.stats as st
import numpy as np

In [14]:
alpha = 0.05
pop_mean = 150
sam_mean = 148
sam_std = 5
n = 25

In [15]:
df = n - 1
df

24

In [16]:
t_calc = (sam_mean - pop_mean) / (sam_std / np.sqrt(n))
t_calc

np.float64(-2.0)

In [17]:
t_table = st.t.ppf(alpha, df)
t_table

np.float64(-1.7108820799094282)

In [18]:
if t_calc > t_table:
    print("The claim of manufracturer is right")
else:
    print("The claim of manifracturer is wrong")

The claim of manifracturer is wrong


### Example 2:
A company wants to test whether there is a difference in productivity between two teams. 
They randomly select 20 employees from each team and record their productivity scores. 
The mean productivity for Team A is 80 with a standard deviation of 5, while the mean 
productivity score for Team B is 75 with a standard deviation of 6. Test at 5% level of 
significance whether there is a difference productivity between two teams.

In [19]:
import numpy as np
from scipy.stats import t

In [20]:
level_of_significance = 5 / 100 # 5%
nA = nB = 20
mean_A = 80
std_A = 5
mean_B = 75
std_B = 6


In [21]:
alpha = level_of_significance / 2 # It is two tailed
df = nA - 1 + nB - 1

In [22]:
t_table = t.ppf(alpha, df) # Testing for left tail
t_calc = (mean_A - mean_B) / np.sqrt((np.square(std_A) / nA) + np.square(std_B) / nB)
print("t_table =", t_table, "and t_calc =", t_calc)

t_table = -2.0243941639119694 and t_calc = 2.862991671569341


In [23]:
if t_calc > t_table:
    print("Productivity of A != Productivity of B")
else:
    print("Productivity of A = Productivity of B")

Productivity of A != Productivity of B


### Example 3:
A company wants to test whether a new training program improves the typing speed of its employees. 
The typing speed of 20 employees was recorded before and after the training program. The data is 
given below. Test at a 5% level of significance whether the training program has an effect on the 
typing speed of the employees.
- Before: 50, 60, 45, 65, 55, 70, 40, 75, 80, 65, 70, 60, 50, 55, 45, 75, 60, 50, 65, 70</li>
- After: 60, 70, 55, 75, 65, 80, 50, 85, 90, 70, 75, 65, 55, 60, 50, 80, 65, 55, 70, 75</li>



In [24]:
import numpy as np
from scipy.stats import t

In [25]:
before = np.array([50, 60, 45, 65, 55, 70, 40, 75, 80, 65, 70, 60, 50, 55, 45, 75, 60, 50, 65, 70])
after = np.array([60, 70, 55, 75, 65, 80, 50, 85, 90, 70, 75, 65, 55, 60, 50, 80, 65, 55, 70, 75])
level_of_significance = 5 / 100 # 5%
n = 20

In [26]:
alpha = level_of_significance / 2 # It is two tailed
df = n - 1

In [27]:
mean_before = np.mean(before)
mean_after = np.mean(after)
std_before = np.std(before)
std_after = np.std(after)

In [28]:
t_table = t.ppf(1-alpha, df) # Testing for right tail
t_calc = (mean_after - mean_before) / np.sqrt((np.square(std_after) + np.square(std_before)) / n)
print(f"t_table = {t_table} and t_calc = {t_calc}")

t_table = 2.093024054408263 and t_calc = 2.061200527128206


In [29]:
if t_calc > t_table:
    print("The training program is effective")
else:
    print("The training program is not effective")

The training program is not effective


## 3. Chi Square Test

### Example 1:
A fair dice is rolled 120 times and the following results are obtained:  
Face 1: 22 times  
Face 2: 17 times  
Face 3: 20 times  
Face 4: 26 times  
Face 5: 22 times  
Face 6: 13 times  
Test at 5% level of significance whether the dice is fair.

In [30]:
import numpy as np
from scipy.stats import chi2

In [31]:
observed = np.array([22, 17, 20, 26, 22, 13])
expected = np.array([20, 20, 20, 20, 20, 20])

In [32]:
alpha = 0.05 # Given level of significance is 5%
n = 6 # Total number of possibilities when a dice is rolled

In [33]:
df = n - 1 # degree of freedom

In [34]:
chi_critical = chi2.ppf(1-alpha, df) # Right tailed
chi_calc = np.sum(np.square(observed - expected) / expected)
print(f"chi_critical = {chi_critical} and chi_calc = {chi_calc}")

chi_critical = 11.070497693516351 and chi_calc = 5.1000000000000005


In [35]:
if chi_calc > chi_critical:
    print("Dice is not fair")
else:
    print("Dice is fair")

Dice is fair


### Example 2:
A study wa conducted to investigate whether there is a relationship between gender and the 
perferred genre of music. A sample of 235 people was selected, and the data collected is shown 
below. Test at a 5% level of significance whether there is significant association between gender 
and music preference.
|               | Pop           | Hip Hop       | Classical     | Rock          |
| ------------- | ------------- |---------------|---------------|---------------|
| Male          | 40            | 45            | 25            | 10            |
| Female        | 35            | 30            | 20            | 30            |

In [36]:
import numpy as np
from scipy.stats import chi2

In [37]:
alpha = 0.05 # Given level of significance is 5%
n = 235 # Sample of 235 people was selected

In [38]:
rows = 2 # From table
columns = 4

In [39]:
row1 = np.array([40, 45, 25, 10])
row2 = np.array([35, 30, 20, 30])

In [40]:
df = (rows - 1) * (columns - 1)
df

3

In [41]:
chi_critical = chi2.ppf(alpha, df)
print("chi_critical", chi_critical)

chi_critical 0.35184631774927144


In [42]:
sum_row1 = np.sum(row1)
sum_row2 = np.sum(row2)
sum_rows = np.array([sum_row1, sum_row2]) # Create an array of sum of rows
sum_rows

array([120, 115])

In [43]:
sum_columns = row1 + row2 # Find sum of all columns at once in the array
sum_columns

array([75, 75, 45, 40])

In [44]:
# Find the expected values
expected = []
for i in sum_rows:
    for j in sum_columns:
        expected.append(i*j/n)

expected

[np.float64(38.297872340425535),
 np.float64(38.297872340425535),
 np.float64(22.97872340425532),
 np.float64(20.425531914893618),
 np.float64(36.702127659574465),
 np.float64(36.702127659574465),
 np.float64(22.02127659574468),
 np.float64(19.574468085106382)]

In [45]:
# Get observed values
observed = np.append(row1, row2)
observed

array([40, 45, 25, 10, 35, 30, 20, 30])

In [46]:
chi_calc = np.sum(np.square(observed - expected) / expected)
print("chi_calc", chi_calc)

chi_calc 13.788747987117553


In [47]:
if chi_calc > chi_critical:
    print("There is association between gender and music preference")
else:
    print("There is association between gender and music preference")

There is association between gender and music preference
